Fix type of raised errors, these are NSStrings, not NSErrors.
This bug caused:
NSInvalidArgumentException: -[__NSCFConstantString code]: unrecognized selector sent to instance 0x7fff7736ce00

The solution will still show the NSError details if somebody decides to
raise an NSError instead of an NSString, going in against the documented
usage of raise (see Apple docs on NSException):
+ (void)raise:(NSString *)name format:(NSString *)format, ...